"""Infrastructure-free trading domain contracts."""

from trading.domain.order_lifecycle import (
    CancellationConfirmed,
    CancellationRejected,
    CancellationRequested,
    ConfirmedFill,
    InvalidOrderTransition,
    OrderLifecycle,
    OrderLifecycleEvent,
    OrderLifecycleState,
    SubmissionAcknowledged,
    SubmissionAmbiguous,
    SubmissionEvent,
    SubmissionFailed,
    new_order_lifecycle,
    reduce_order_lifecycle,
    submission_event_from_report,
)
from trading.domain.orders import (
    OrderIntent,
    OrderSide,
    OrderType,
    RetrySafety,
    SubmissionReport,
    SubmissionStatus,
)
from trading.domain.paper_economics import (
    InvalidPaperEconomicTransition,
    PaperCostLot,
    PaperEconomics,
    PaperFeeTotal,
    PaperFillRecord,
    PaperLotMethod,
    new_paper_economics,
    reduce_paper_economics,
)
from trading.domain.paper_settlement import (
    InvalidPaperSettlement,
    PaperAssetAmount,
    PaperLinearInstrument,
    PaperSettlement,
    PaperSettlementCheckpoint,
    PaperSettlementDisposition,
    settle_paper_fill,
)
from trading.domain.positions import (
    InvalidPositionTransition,
    Position,
    PositionEffect,
    PositionExitContext,
    PositionFill,
    PositionInstruction,
    PositionSide,
    PositionState,
    TakeProfitProfile,
    new_position,
    position_fill_from_lifecycle,
    reduce_position,
)
from trading.domain.risk import RiskDecision
from trading.domain.signals import Signal, SignalAction

__all__ = [
    "CancellationConfirmed",
    "CancellationRejected",
    "CancellationRequested",
    "ConfirmedFill",
    "InvalidOrderTransition",
    "InvalidPaperEconomicTransition",
    "InvalidPaperSettlement",
    "InvalidPositionTransition",
    "OrderIntent",
    "OrderLifecycle",
    "OrderLifecycleEvent",
    "OrderLifecycleState",
    "OrderSide",
    "OrderType",
    "PaperCostLot",
    "PaperAssetAmount",
    "PaperEconomics",
    "PaperFeeTotal",
    "PaperFillRecord",
    "PaperLotMethod",
    "PaperLinearInstrument",
    "PaperSettlement",
    "PaperSettlementCheckpoint",
    "PaperSettlementDisposition",
    "Position",
    "PositionEffect",
    "PositionExitContext",
    "PositionFill",
    "PositionInstruction",
    "PositionSide",
    "PositionState",
    "RetrySafety",
    "RiskDecision",
    "Signal",
    "SignalAction",
    "SubmissionReport",
    "SubmissionAcknowledged",
    "SubmissionAmbiguous",
    "SubmissionEvent",
    "SubmissionFailed",
    "SubmissionStatus",
    "TakeProfitProfile",
    "new_order_lifecycle",
    "new_paper_economics",
    "new_position",
    "position_fill_from_lifecycle",
    "reduce_order_lifecycle",
    "reduce_paper_economics",
    "reduce_position",
    "settle_paper_fill",
    "submission_event_from_report",
]
