"""
Event type definitions for the ELVIS Trading Bot.
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional
from .event_bus import Event, EventPriority


@dataclass
class MarketDataEvent(Event):
    """Event for market data updates."""
    symbol: str = ""
    price: float = 0.0
    volume: float = 0.0
    bid: Optional[float] = None
    ask: Optional[float] = None
    indicators: Dict[str, float] = field(default_factory=dict)
    
    @property
    def event_type(self) -> str:
        return "market_data"


@dataclass
class TradingSignalEvent(Event):
    """Event for trading signals generated by strategies."""
    symbol: str = ""
    signal_type: str = ""  # 'buy', 'sell', 'hold'
    strength: float = 0.0  # Signal strength [0, 1]
    strategy_name: str = ""
    price: float = 0.0
    quantity: Optional[float] = None
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    reasons: List[str] = field(default_factory=list)
    
    @property
    def event_type(self) -> str:
        return "trading_signal"


@dataclass
class OrderEvent(Event):
    """Event for order-related activities."""
    order_id: str = ""
    symbol: str = ""
    order_type: str = ""  # 'market', 'limit', 'stop_loss', 'take_profit'
    side: str = ""  # 'buy', 'sell'
    quantity: float = 0.0
    price: Optional[float] = None
    status: str = 'pending'  # 'pending', 'filled', 'partial', 'cancelled', 'rejected'
    filled_quantity: float = 0.0
    average_price: float = 0.0
    commission: float = 0.0
    error_message: Optional[str] = None
    
    @property
    def event_type(self) -> str:
        return "order"


@dataclass
class RiskEvent(Event):
    """Event for risk management alerts and actions."""
    risk_type: str = ""  # 'position_size', 'drawdown', 'exposure', 'volatility'
    severity: str = ""  # 'info', 'warning', 'critical'
    current_value: float = 0.0
    threshold_value: float = 0.0
    action_taken: Optional[str] = None
    affected_positions: List[str] = field(default_factory=list)
    
    def __post_init__(self):
        """Set priority based on severity."""
        super().__post_init__()
        if self.severity == 'critical':
            self.priority = EventPriority.CRITICAL
        elif self.severity == 'warning':
            self.priority = EventPriority.HIGH
        else:
            self.priority = EventPriority.NORMAL
    
    @property
    def event_type(self) -> str:
        return "risk"


@dataclass
class SystemEvent(Event):
    """Event for system-level activities and monitoring."""
    system_type: str = ""  # 'startup', 'shutdown', 'error', 'performance', 'health'
    component: str = ""  # Component name (e.g., 'strategy', 'executor', 'data_feed')
    status: str = ""  # 'ok', 'warning', 'error', 'critical'
    message: str = ""
    metrics: Dict[str, Any] = field(default_factory=dict)
    
    @property
    def event_type(self) -> str:
        return "system"


@dataclass
class PositionEvent(Event):
    """Event for position updates."""
    symbol: str = ""
    position_id: str = ""
    quantity: float = 0.0
    entry_price: float = 0.0
    current_price: float = 0.0
    unrealized_pnl: float = 0.0
    realized_pnl: float = 0.0
    position_type: str = 'long'  # 'long', 'short'
    status: str = 'open'  # 'open', 'closed', 'partial'
    
    @property
    def event_type(self) -> str:
        return "position"


@dataclass
class BalanceEvent(Event):
    """Event for balance updates."""
    asset: str = ""
    free_balance: float = 0.0
    locked_balance: float = 0.0
    total_balance: float = 0.0
    change_amount: float = 0.0
    change_reason: Optional[str] = None
    
    @property
    def event_type(self) -> str:
        return "balance"


@dataclass
class PerformanceEvent(Event):
    """Event for performance metrics updates."""
    metric_type: str = ""  # 'sharpe', 'returns', 'drawdown', 'win_rate'
    value: float = 0.0
    period: str = ""  # '1h', '1d', '1w', '1m'
    benchmark_value: Optional[float] = None
    details: Dict[str, Any] = field(default_factory=dict)
    
    @property
    def event_type(self) -> str:
        return "performance"


@dataclass
class ModelEvent(Event):
    """Event for model-related activities."""
    model_name: str = ""
    action: str = ""  # 'trained', 'deployed', 'prediction', 'error', 'drift_detected'
    accuracy: Optional[float] = None
    confidence: Optional[float] = None
    prediction: Optional[Any] = None
    error_details: Optional[str] = None
    
    @property
    def event_type(self) -> str:
        return "model"


@dataclass
class BacktestEvent(Event):
    """Event for backtesting activities."""
    backtest_id: str = ""
    status: str = ""  # 'started', 'running', 'completed', 'failed'
    progress: float = 0.0  # 0-100
    current_date: Optional[datetime] = None
    results: Dict[str, Any] = field(default_factory=dict)
    
    @property
    def event_type(self) -> str:
        return "backtest"


@dataclass
class NotificationEvent(Event):
    """Event for user notifications."""
    notification_type: str = ""  # 'trade', 'alert', 'system', 'performance'
    title: str = ""
    message: str = ""
    channels: List[str] = field(default_factory=list)  # ['telegram', 'email', 'webhook']
    sent_status: Dict[str, bool] = field(default_factory=dict)
    
    @property
    def event_type(self) -> str:
        return "notification"


# Event type mapping for easy access
EVENT_TYPES = {
    'market_data': MarketDataEvent,
    'trading_signal': TradingSignalEvent,
    'order': OrderEvent,
    'risk': RiskEvent,
    'system': SystemEvent,
    'position': PositionEvent,
    'balance': BalanceEvent,
    'performance': PerformanceEvent,
    'model': ModelEvent,
    'backtest': BacktestEvent,
    'notification': NotificationEvent,
}
