#!/bin/bash
echo "============================================="
echo "Starting ELVIS Trading System Dashboard"
echo "============================================="
echo ""
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export PYTHONPATH="$SCRIPT_DIR:$PYTHONPATH"
echo "🚀 Starting dashboard..."
python3.14 "$SCRIPT_DIR/run_dashboard.py"
echo ""
echo "============================================="
echo "Dashboard Session Ended"
echo "============================================="
