local   postgres                    elvis_bootstrap_admin                       scram-sha-256
local   elvis_paper_v2_rehearsal    elvis_bootstrap_admin                       scram-sha-256
local   all                         all                                         reject
host    elvis_paper_v2_rehearsal   elvis_bootstrap_admin       10.254.90.0/28   scram-sha-256
host    elvis_paper_v2_rehearsal   elvis_v2_migrator           10.254.90.0/28   scram-sha-256
host    elvis_paper_v2_rehearsal   elvis_v2_readiness          10.254.90.0/28   scram-sha-256
host    elvis_paper_v2_rehearsal   elvis_v2_trainer            10.254.90.0/28   scram-sha-256
host    all                         all                         0.0.0.0/0         reject
host    all                         all                         ::/0              reject
